"""add cancel_reason to orders

Revision ID: dab26ea64d9c
Revises: d0ba8686bcaf
Create Date: 2026-06-26 15:53:32.723758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab26ea64d9c'
down_revision: Union[str, Sequence[str], None] = 'd0ba8686bcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancel_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancel_reason')
    # ### end Alembic commands ###
